# Source: lighthouse/templates/oauthsecret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: my-kubernetes-secret-name
spec:
  backendType: gcpSecretsManager
  projectId: foo
  data:
  - name: my-kubernetes-secret-name
    key: my-gsm-secret-name
    property: oauth
    version: 1
  template:
    metadata:
      labels:
        app: lighthouse-lighthouse
        chart: "lighthouse-0.0.633"
        release: "lighthouse"
        heritage: "Helm"
    type: Opaque