apiVersion: v1
kind: Service
metadata:
  name: app1
  namespace: myapps
  labels:
    chart: "app1-0.0.12"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: app1-app1
