apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
spec:
  groups:
  - owner: myorg
    provider: https://github.com
    providerKind: github
    providerName: github
    repositories:
      - name: myapp
        jenkins:
          server: myjenkins
          xmlTemplate: jenkins/templates/default.xml.gotmpl
      - name: another
        jenkins:
          server: myjenkins
          xmlTemplate: jenkins/templates/default.xml.gotmpl
