apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
spec:
  jenkinsServers:
  - server: myjenkins
    groups:
    - owner: myorg
      provider: https://github.com
      providerKind: github
      providerName: github
      repositories:
        - name: myapp
        - name: another
