trigger:
  trustedOrg: roadrunner-corp
approve:
  lgtmActsAsApprove: true
  ignoreReviewState: false
externalPlugins:
  entries:
  - name: jx-app-cheese
    endpoint: http://jx-app-cheese
schedulerAgent:
  agent: prow
policy:
  protectTested: true
merger:
  blockerLabel: hold
  prStatusBaseUrl: http://fakeurl
  maxGoroutines: 5
  policy:
    fromBranchProtection: true
    required-contexts:
      entries:
        - context1
        - context2
    required-if-present-contexts:
      entries:
        - context55
        - context66
        - context77
    optional-contexts:
      entries:
        - opt1
postsubmits:
  entries:
  - name: release
    context: ""
    branches:
      - master
    agent: tekton

presubmits:
  entries:
  - name: integration
    agent: tekton
    always_run: true
    context: integration
    rerun_command: /test this
    trigger: (?m)^/test( all| this),?(\s+|$)
    queries:
      - labels:
          entries:
            - approved
        missingLabels:
          entries:
          - do-not-merge
          - do-not-merge/hold
          - do-not-merge/work-in-progress
          - needs-ok-to-test
          - needs-rebase
    policy:
      protect: true
      requiredStatusChecks:
        contexts:
          entries:
          - integration
plugins:
  entries:
  - config-updater
  - approve
  - assign
  - blunderbuss
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - trigger
  - wip
  - heart
  - override
