filepath: ""
repositories:
- name: jenkins-x
  url: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: jenkins
  url: https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/chart
releases:
- chart: jenkins-x/jx-test-collector
  namespace: jx
- chart: jenkins/jenkins-operator
  namespace: jx
templates: {}
renderedvalues: {}
