filepath: ""
repositories:
- name: dev
  url: http://bucketrepo/bucketrepo/charts/
- name: cdf
  url: https://cdfoundation.github.io/tekton-helm-chart
- name: jx3
  url: https://storage.googleapis.com/jenkinsxio/charts
releases:
- chart: cdf/tekton-pipeline
  version: 0.0.5
  name: tekton-pipeline
  namespace: tekton-pipelines
  values:
  - versionStream/charts/cdf/tekton-pipeline/values.yaml.gotmpl
  forceNamespace: ""
  skipDeps: null
- chart: dev/dummy
  version: 1.2.3
  name: dummy
  namespace: jx
  forceNamespace: ""
  skipDeps: null
- chart: jx3/jx-build-controller
  name: jx-build-controller
  namespace: jx
  forceNamespace: ""
  skipDeps: null
templates: {}
missingFileHandler: ""
renderedvalues: {}