filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx
repositories:
- name: jx3
  url: https://storage.googleapis.com/jenkinsxio/charts
- name: dev
  url: http://bucketrepo/bucketrepo/charts/
releases:
- chart: jx3/bucketrepo
  name: bucketrepo
  values:
  - jx-values.yaml
- chart: dev/dummy
  version: 1.2.3
  name: dummy
  values:
  - jx-values.yaml
- chart: jx3/jx-build-controller
  name: jx-build-controller
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}