filepath: ""
repositories:
- name: dev
  url: http://bucketrepo/bucketrepo/charts/
- name: cdf
  url: https://cdfoundation.github.io/tekton-helm-chart
releases:
- chart: cdf/tekton-pipeline
  version: 0.0.5
  name: tekton-pipeline
  namespace: tekton-pipelines
- chart: dev/dummy
  version: 1.2.3
  name: dummy
  namespace: jx
templates: {}
missingFileHandler: ""