filepath: ""
repositories:
- name: doesnotexist
  url: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: cdf
  url: https://cdfoundation.github.io/tekton-helm-chart
- name: jenkins-x
  url: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: external-secrets
  url: https://godaddy.github.io/kubernetes-external-secrets
releases:
- chart: cdf/tekton-pipeline
  version: 0.0.5
  name: tekton-pipeline
  namespace: tekton-pipelines
  values:
  - versionStream/charts/cdf/tekton-pipeline/values.yaml.gotmpl
- chart: jenkins-x/jxboot-helmfile-resources
  version: 1.0.1
  name: jxboot-helmfile-resources
  namespace: jx
  values:
  - versionStream/charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
- chart: bitnami/external-dns
  version: 3.2.0
  name: external-dns
  namespace: foo
  values:
  - versionStream/charts/bitnami/external-dns/values.yaml.gotmpl
  - values/external-dns/values.yaml
- chart: external-secrets/kubernetes-external-secrets
  version: 5.2.0
  name: kubernetes-external-secrets
  namespace: external-secrets
  values:
  - versionStream/charts/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl
  - values/kubernetes-external-secrets/values.yaml.gotmpl
- chart: doesnotexist/bucketrepo
  name: bucketrepo
  namespace: jx
templates: {}
missingFileHandler: ""