apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: tekton-pipelines-jx
  namespace: jx
subjects:
- kind: ServiceAccount
  name: tekton-pipelines
  namespace: jx
roleRef:
  kind: ClusterRole
  name: tekton-pipelines
  apiGroup: rbac.authorization.k8s.io