filepath: ""
repositories:
- name: doesnotexist
  url: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: jenkins-x
  url: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: external-secrets
  url: https://godaddy.github.io/kubernetes-external-secrets
releases:
- chart: jenkins-x/tekton
  version: 0.0.56
  name: tekton
  namespace: jx
  values:
  - versionStream/charts/jenkins-x/tekton/values.yaml.gotmpl
- chart: jenkins-x/jxboot-helmfile-resources
  version: 0.0.255
  name: jxboot-helmfile-resources
  namespace: jx
- chart: bitnami/external-dns
  version: 3.1.2
  name: external-dns
  namespace: foo
  values:
  - values/external-dns/values.yaml
- chart: external-secrets/kubernetes-external-secrets
  version: 4.0.0
  name: kubernetes-external-secrets
  namespace: external-secrets
  values:
  - values/kubernetes-external-secrets/values.yaml.gotmpl
- chart: doesnotexist/bucketrepo
  name: bucketrepo
  namespace: jx
templates: {}
missingFileHandler: ""