filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: secret-infra
repositories:
- name: jx3
  url: https://storage.googleapis.com/jenkinsxio/charts
releases:
- chart: jx3/vault-instance
  name: vault-instance
  values:
  - jx-values.yaml
- chart: jx3/pusher-wave
  name: pusher-wave
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
