releases:
  - chart: jenkins-x/tekton
  - chart: jenkins-x/jxboot-helmfile-resources
  - chart: bitnami/external-dns
    namespace: foo
  # test using a local repo prefix and URL
  - chart: doesnotexist/bucketrepo
repositories:
  - name: doesnotexist
    url: https://storage.googleapis.com/chartmuseum.jenkins-x.io
