jobs:
  plugins:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            TARGET: linux
            BINARY: jx-gitops
          - os: macos-latest
            TARGET: darwin
            BINARY: jx-gitops
          - os: windows-latest
            TARGET: win
            BINARY: jx-gitops-windows-amd64.exe

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - run: make ${{ matrix.target }}
      - run: |
          ./build/${{ matrix.target }}/${{ matrix.binary }} version
          ./build/${{ matrix.target }}/${{ matrix.binary }} plugin upgrade
          ./build/${{ matrix.target }}/${{ matrix.binary }} --help
          ls -al ~/.jx3/plugins/bin

on:
  pull_request:
    branches:
    - main
    - master
