trigger:
  trusted_org: roadrunner-corp
  join_org_url: http://org-url
  ignore_ok_to_test: true
  only_org_members: true

external_plugins:
  entries:
    - name: jx-app-cheese
      endpoint: http://jx-app-cheese
    - name: jx-app-jacoco
      endpoint: http://jx-app-jacoco

lgtm:
  review_acts_as_lgtm: false
  store_tree_hash: false
  trusted_team_for_sticky_lgtm: team1

plugins:
  entries:
    - trigger
    - wip
    - heart
    - override